"""
muonGun_pT_1000_5000 with a 2 GeV pT cut.

source /cvmfs/muoncollider.cern.ch/release/2.9/setup.sh
export PYTHONPATH=/home/sdouglas/muon_analysis/pypackages:$PYTHONPATH
python3 muon_reco_analysis.py OR
nohup python3 muon_reco_analysis.py > output.log 2>&1 &

NEW FILE NAMES NOW, CHANGE IF NEEDED REMEMBER THIS

"""

# ── stdlib ─────────────────────────────────────────────────────────────────
import glob, os, sys
from dataclasses import dataclass, field
# from typing import Optional   # not used

# ── third-party ────────────────────────────────────────────────────────────
import numpy as np
import matplotlib
matplotlib.use("Agg")          # backend
import matplotlib.pyplot as plt
# import matplotlib.gridspec as gridspec   # not used
from scipy.optimize import curve_fit
# from scipy.stats import norm as scipy_norm   # not used

# ── pyLCIO ─────────────────────────────────────────────────────────────────
try:
    from pyLCIO import IOIMPL, EVENT, UTIL
except ImportError:
    sys.exit("pyLCIO not found. Activate your key4hep / ILCSoft environment first.")

# ════════════════════════════════════════════════════════════════════════════
#  CONFIG  ← edit here cfg short hand
# ════════════════════════════════════════════════════════════════════════════
CONFIG = dict(
    # --- file globs ---
    # no_bib_glob is unused
    # bib_glob is unused, we read from filelist.txt instead because glob
    # doesn't work on worker nodes where /ospool is not locally mounted
    # having a lot of trouble with ROOT using condor
    no_bib_glob   = None,
    bib_glob      = None,
    filelist      = "filelist.txt",   # generated by: ls /ospool/.../muonGun_pT_1000_5000/*.slcio > filelist.txt

    # xrootd prefix: prepended to each file path when running on OSG worker nodes
    # that cannot directly mount /ospool. set to "" when running on ap23 directly.
    # set to "root://ospool-hf.osg-htc.org/" for batch jobs (currently broken
    # pyLCIO's LCReader does not support xrootd URLs, I just run on ap3)
    xrootd_prefix = "",

    # --- collection names ---
    # these were discovered by printing event.getCollectionNames() on the first event
    # see print_collections.py
    mc_col_name    = "MCParticle",           # truth particles
    pfo_col_name   = "PandoraPFOs",          # pandora particle flow objects (reco)
    link_col_name  = "MCParticlePandoraPFOs",# truth-to-reco association collection
    track_col_name = "SiTracks",             # silicon tracker track fits

    # --- matching ---
    # dr_cut: maximum deltaR = sqrt(deta^2 + dphi^2)
    # 0.1 is a standard choice for charged particle ILC
    # sam suggested even 0.01 might be more appropriate for clean muon matching
    # currently using 0.1
    dr_cut   = 0.1,

    # muon PDG code. 13 = mu-, -13 = mu+ abs() used to get both in one sweep
    muon_pdg = 13,

    # --- pT cut ---
    # we only analyze events where the truth muon has pT > 2 GeV.
    # this is because the dataset covers pT 1-5 GeV but the low end (1-2 GeV)
    # is impacted by BIB (was a worse fit initially)
    pt_cut_mev = 2000,

    # --- binning ---
    # 13 bin edges = 12 bins across the 2-5 GeV
    # all values in MeV
    pt_bins            = np.linspace(2000, 5000, 13),
    min_events_per_bin = 15,   # minimum events in a bin, trying to Gaussian

    # --- output ---
    out_dir = "plots",   # directory where plots are saved
    dpi     = 150,       # dots per inch for saved figures — 150 is good for screen viewing

    # --- debug ---
    # making sure all needed collections are there
    print_collections = False,
    # can set to ~50 for test run SET MAX FILES LINE
    max_files = None,
)
# ════════════════════════════════════════════════════════════════════════════


# ── helpers ──────────────────────────────────────────────────────────────────

def pt_eta_phi(px, py, pz):
    
    """convert cartesian momentum to cylindrical
    pt  = transverse momentum, perpendicular to the beam axis z
          this is what the tracker measures via track curvature in the B field
    eta = pseudorapidity, a measure of the polar angle from the beam axis
          eta=0 is perpendicular to beam, eta=+/-inf is along the beam
          defined as -ln(tan(theta/2)) where theta is the polar angle
    phi = azimuthal angle in the transverse (x,y) plane
    """
    
    pt  = np.sqrt(px**2 + py**2)
    eta = -np.log(np.tan(0.5 * np.arctan2(pt, pz))) if pt > 0 else 0.0
    phi = np.arctan2(py, px)
    return pt, eta, phi

def delta_r(eta1, phi1, eta2, phi2):
    
    """compute the angular distance deltaR between two particles
    deltaR = sqrt(deta^2 + dphi^2) how close two particles are in angle space
    used for reco
    the dphi wrapping ensures we handle the -pi/+pi B.C.
    """
    dphi = phi1 - phi2
    dphi = (dphi + np.pi) % (2 * np.pi) - np.pi   # range [-pi, pi]
    return np.sqrt((eta1 - eta2)**2 + dphi**2)

def gaussian(x, A, mu, sigma):
    
    """standard gaussian function used for residuals
    A     = amplitude (peak height, matched to histogram bin count)
    mu    = mean (the bias of the distribution)
    sigma = standard deviation, resolution
    """
    return A * np.exp(-0.5 * ((x - mu) / sigma)**2)


# ── data container ───────────────────────────────────────────────────────────

@dataclass
class EventData:
    
    """stores per-event truth and reco quantities accumulated across all files
    lists are appended to for each truth muon found. matched=True means a reco
    PFO was found within dr_cut of the truth muon. matched=False contributes
    to the efficiency denominator but not the resolution numerator
    pull quantities (d0, z0, phi, tanlam, omega) are track parameter pulls
    from the silicon tracker and are only filled if SiTracksMCTruthLink is 
    available
    """
    true_pt  : list = field(default_factory=list)
    reco_pt  : list = field(default_factory=list)
    true_eta : list = field(default_factory=list)
    reco_eta : list = field(default_factory=list)
    true_phi : list = field(default_factory=list)
    reco_phi : list = field(default_factory=list)
    matched  : list = field(default_factory=list)   # bool: was this truth muon matched?
    pull_d0    : list = field(default_factory=list)
    pull_z0    : list = field(default_factory=list)
    pull_phi   : list = field(default_factory=list)
    pull_tanlam: list = field(default_factory=list)
    pull_omega : list = field(default_factory=list)

    def arrays(self):
        
        """convert lists to numpy arrays. matched pairs are filtered using the
        boolean mask m, unmatched events are excluded from resolution/angular
        plots but kept in all_true_pt/all_matched for efficiency calculation"""
        
        m = np.array(self.matched, dtype=bool)
        return dict(
            true_pt  = np.array(self.true_pt)[m],
            reco_pt  = np.array(self.reco_pt)[m],
            true_eta = np.array(self.true_eta)[m],
            reco_eta = np.array(self.reco_eta)[m],
            true_phi = np.array(self.true_phi)[m],
            reco_phi = np.array(self.reco_phi)[m],
            all_true_pt = np.array(self.true_pt),   # includes unmatched, for efficiency denom
            all_matched = m,
            pull_d0     = np.array(self.pull_d0),
            pull_z0     = np.array(self.pull_z0),
            pull_phi    = np.array(self.pull_phi),
            pull_tanlam = np.array(self.pull_tanlam),
            pull_omega  = np.array(self.pull_omega),
        )


# ── reader ───────────────────────────────────────────────────────────────────

def process_files(file_list: list, cfg: dict) -> EventData:
    
    # LINES FOR MATCHING EDITING
    """read all LCIO files, extract truth muons and matched reco PFOs
    for each event:
      1. get truth muons from MCParticle (level 1, pT > pt_cut_mev)
      2. get reco PFOs from PandoraPFOs (filtered to tracked particles only)
      3. try MCParticlePandoraPFOs link collection for matching
      4. fall back to min-deltaR matching if link collection fails
      5. optionally fill track parameter pulls if SiTracksMCTruthLink exists
    """
    
    data   = EventData() # class
    reader = IOIMPL.LCFactory.getInstance().createLCReader()
    # https://ilcsoft.desy.de/LCIO/current/doc/doxygen_api/html/classIOIMPL_1_1LCFactory.html
   
    if cfg["max_files"]:
        file_list = file_list[:cfg["max_files"]]

    # prepend xrootd prefix if running on worker nodes without /ospool mount
    prefix = cfg.get("xrootd_prefix", "")
    if prefix:
        file_list = [prefix + f for f in file_list]

    print(f"  Processing {len(file_list)} files …")

    n_evt = 0
    for fpath in file_list:
        try:
            reader.open(fpath)
        except Exception as e:
            print(f"  WARNING: could not open {fpath}: {e}")
            continue

        while True:
            try:
                event = reader.readNextEvent() # using ILC reader
            except Exception:
                break
            if event is None:
                break
            n_evt += 1

            # print all collection names in the first event (debugging)
            # set print_collections=True in CONFIG to enable, I have it as false
            if cfg["print_collections"] and n_evt == 1:
                cols = event.getCollectionNames()
                print("collections in first event:")
                for col in cols:
                    print(f"  {col}")

            # ── get truth muons ───────────────────────────────────
            try:
                mc_col = event.getCollection(cfg["mc_col_name"]) #MCParticle
            except Exception:
                continue   # skip event if MCParticle collection missing

            truth_muons = []
            for i in range(mc_col.getNumberOfElements()):
                mc = mc_col.getElementAt(i)
                # generator status 1 = primary stable particle from the gun
                # status 2 = decayed, status 3 = documentation
                # abs(PDG) gets both mu- and mu+
                if abs(mc.getPDG()) == cfg["muon_pdg"] and mc.getGeneratorStatus() == 1:
                    p = mc.getMomentum()
                    pt, eta, phi = pt_eta_phi(p[0], p[1], p[2])
                    # apply 2 GeV pT cut
                    if pt < cfg.get("pt_cut_mev", 0):
                        continue
                    truth_muons.append(dict(mc=mc, pt=pt, eta=eta, phi=phi))

            # ── get reco PFOs ─────────────────────────────────────
            try:
                pfo_col = event.getCollection(cfg["pfo_col_name"]) #PandoraPFOs
            except Exception:
                # if PandoraPFOs is missing, mark all truth muons as unmatched
                for tm in truth_muons:
                    data.true_pt.append(tm["pt"])
                    data.true_eta.append(tm["eta"])
                    data.true_phi.append(tm["phi"])
                    data.reco_pt.append(np.nan)
                    data.reco_eta.append(np.nan)
                    data.reco_phi.append(np.nan)
                    data.matched.append(False)
                continue

            pfos = []
            for i in range(pfo_col.getNumberOfElements()):
                pfo = pfo_col.getElementAt(i)

                # key BIB filter: require at least one associated track
                # muons are charged and always produce a track in the silicon tracker
                # BIB neutrals (neutrons type=2112, photons type=22) have nTracks=0
                # and were responsible for the -100% spike in the residual plot
                
                if pfo.getTracks().size() == 0: # this may be redundant with pdg condition in place
                    continue

                # additionally require the PFO PDG type matches the muon PDG
                # this filters BIB pions (type=-211) and electrons (type=11)
                # that happen to have a track but are not muons
                # we saw these in the diagnostic: type=-211 with res~7% being
                # incorrectly matched to truth muons
                
                if abs(pfo.getType()) != cfg["muon_pdg"]:
                    continue

                p = pfo.getMomentum()
                pt, eta, phi = pt_eta_phi(p[0], p[1], p[2])
                pfos.append(dict(pfo=pfo, pt=pt, eta=eta, phi=phi))

            # ── try link collection for matching ──────────────────
            # MCParticlePandoraPFOs is an LCRelation collection associating
            # MCParticles to PFOs with a weight. higher weight = more of the
            # PFO energy came from that MC particle
            # in practice for the muon gun this often fails (navigator returns
            # 0 relations) so we fall back to deltaR matching
            
            link_map = {}   # maps pfo index → mc object
            if cfg["link_col_name"]:
                try:
                    link_col = event.getCollection(cfg["link_col_name"])
                    nav = UTIL.LCRelationNavigator(link_col)
                    for i, pd in enumerate(pfos):
                        rels = nav.getRelatedToObjects(pd["pfo"])
                        wts  = nav.getRelatedToWeights(pd["pfo"])
                        if rels.size() > 0:
                            # take the MC particle with the highest weight
                            best_idx = int(np.argmax([wts.elementAt(j) for j in range(wts.size())]))
                            link_map[i] = rels.elementAt(best_idx)
                except Exception:
                    pass   # link collection unavailable — fall through to deltaR

            # ── match each truth muon to a reco PFO ──────────────
            # once a PFO is used, it can't be matched again
            # first tries link collection (exact), then falls back to min-deltaR
            used_pfo = set()
            for tm in truth_muons:
                data.true_pt.append(tm["pt"])
                data.true_eta.append(tm["eta"])
                data.true_phi.append(tm["phi"])

                matched_pfo = None

                # try link collection first
                for pi, pd in enumerate(pfos):
                    if pi in used_pfo:
                        continue
                    if pi in link_map and link_map[pi] is tm["mc"]:
                        matched_pfo = (pi, pd)
                        break

                # fall back to min-deltaR if link collection gave nothing
                if matched_pfo is None:
                    best_dr, best_pi, best_pd = cfg["dr_cut"], None, None
                    for pi, pd in enumerate(pfos):
                        if pi in used_pfo:
                            continue
                        dr = delta_r(tm["eta"], tm["phi"], pd["eta"], pd["phi"])
                        if dr < best_dr:
                            best_dr, best_pi, best_pd = dr, pi, pd
                    if best_pi is not None:
                        matched_pfo = (best_pi, best_pd)

                if matched_pfo is not None:
                    pi, pd = matched_pfo
                    used_pfo.add(pi)
                    data.reco_pt.append(pd["pt"])
                    data.reco_eta.append(pd["eta"])
                    data.reco_phi.append(pd["phi"])
                    data.matched.append(True)
                else:
                    # no match found within dr_cut — counts as inefficiency
                    data.reco_pt.append(np.nan)
                    data.reco_eta.append(np.nan)
                    data.reco_phi.append(np.nan)
                    data.matched.append(False)

            # ──track parameter pulls (optional) ──────────────────
            # pulls measure how well-calibrated the track fit uncertainties are
            # a pull = (measured - truth) / uncertainty should be a unit gaussian
            # if the errors are correct. only filled if SiTracksMCTruthLink exists
            # track parameters at the IP (interaction point):
            #   d0     = transverse impact parameter (closest approach in xy plane)
            #   z0     = longitudinal impact parameter (closest approach along z)
            #   phi    = azimuthal angle of track at closest approach
            #   tanlam = tan(lambda) where lambda is the dip angle from xy plane
            #   omega  = signed curvature = q/R (sign gives charge, magnitude gives pT)
            
            try:
                trk_col = event.getCollection(cfg["track_col_name"])
                mc_trk_nav = None
                try:
                    # SiTracksMCTruthLink links silicon tracks to MC particles
                    mc_trk_col = event.getCollection("SiTracksMCTruthLink")
                    mc_trk_nav = UTIL.LCRelationNavigator(mc_trk_col)
                except Exception:
                    pass   # link not available — pulls will be empty

                for i in range(trk_col.getNumberOfElements()):
                    trk   = trk_col.getElementAt(i)
                    state = trk.getTrackState(EVENT.TrackState.AtIP)
                    if state is None:
                        continue

                    # covariance matrix is lower-triangular, packed as a flat array.
                    # diagonal elements give the variance of each parameter:
                    # cov[0]=var(d0), cov[2]=var(phi), cov[5]=var(omega),
                    # cov[9]=var(z0), cov[14]=var(tanlambda)
                    cov = state.getCovMatrix()
                    sig_d0  = np.sqrt(max(cov[0],  0))
                    sig_phi = np.sqrt(max(cov[2],  0))
                    sig_omg = np.sqrt(max(cov[5],  0))
                    sig_z0  = np.sqrt(max(cov[9],  0))
                    sig_tan = np.sqrt(max(cov[14], 0))

                    if mc_trk_nav:
                        mcs = mc_trk_nav.getRelatedToObjects(trk)
                        if mcs.size() == 0:
                            continue
                        mc_p = mcs.elementAt(0)
                        p    = mc_p.getMomentum()
                        pt_mc, _, phi_mc = pt_eta_phi(p[0], p[1], p[2])
                        pz_mc = p[2]
                        # d0 and z0 truth is 0 for particles from the IP
                        if sig_d0  > 0: data.pull_d0.append(state.getD0()  / sig_d0)
                        if sig_phi > 0: data.pull_phi.append((state.getPhi() - phi_mc) / sig_phi)
                        if sig_z0  > 0: data.pull_z0.append(state.getZ0()  / sig_z0)
                        if sig_tan > 0:
                            tan_mc = pz_mc / pt_mc if pt_mc > 0 else 0
                            data.pull_tanlam.append((state.getTanLambda() - tan_mc) / sig_tan)
                        if sig_omg > 0: data.pull_omega.append(state.getOmega() / sig_omg)
            except Exception:
                pass   # track pulls are optional — skip silently if unavailable

        reader.close()

    print(f"  Processed {n_evt} events.")
    return data


# ── plotting ──────────────────────────────────────────────────────────────────

# style dict: colors and labels for each dataset type
# currently only "bib" is used, "no_bib" is reserved for future comparison
STYLE = dict(
    no_bib = dict(color="#2166ac", label="No BIB",  marker="o"),
    bib    = dict(color="#d6604d", label="With BIB (muon gun, $p_T$ 1–5 GeV)", marker="s"),
)

def gauss_fit(values, n_bins=60):
    
    """fit a gaussian to a 1d distribution. returns (mu, sigma, fit_ok)
    fits over a range of +-4 sigma around the mean to exclude far outliers
    uses scipy curve_fit with bounds to prevent unphysical solutions
    falls back to raw mean/std if the fit fails
    """
    if len(values) < 10:
        return np.nan, np.nan, False
    mu0, sig0 = np.mean(values), np.std(values)
    counts, edges = np.histogram(values, bins=n_bins,
                                 range=(mu0 - 4*sig0, mu0 + 4*sig0))
    centers = 0.5 * (edges[:-1] + edges[1:])
    try:
        p0 = [counts.max(), mu0, sig0]
        popt, _ = curve_fit(gaussian, centers, counts, p0=p0,
                            maxfev=5000,
                            bounds=([0, mu0-3*sig0, 0],
                                    [counts.max()*2, mu0+3*sig0, 3*sig0]))
        return popt[1], abs(popt[2]), True
    except Exception:
        return mu0, sig0, False   # return raw stats if fit fails


def plot_pt_resolution(datasets: dict, bins, cfg):
    
    """plot pT resolution (sigma) and bias (mean) vs true pT
    for each pT bin, fits a gaussian to the residual distribution
    (reco_pT - true_pT) / true_pT and extracts mu (bias) and sigma (resolution)
    error bars on resolution use the standard result: err(sigma) = sigma / sqrt(2N)
    """
    fig, axes = plt.subplots(1, 2, figsize=(13, 5))

    for tag, arr in datasets.items():
        st  = STYLE[tag]
        # fractional residual (not in percent !! need mult 100)
        res = (arr["reco_pt"] - arr["true_pt"]) / arr["true_pt"]
        centers, sigmas, sig_errs, means = [], [], [], []

        for lo, hi in zip(bins[:-1], bins[1:]):
            mask = (arr["true_pt"] >= lo) & (arr["true_pt"] < hi)
            if mask.sum() < cfg["min_events_per_bin"]:
                continue   # skip bins with too few events, bad fit otherwise
            mu, sig, ok = gauss_fit(res[mask])
            centers.append(0.5 * (lo + hi))
            sigmas.append(sig * 100)         # convert to percent
            means.append(mu * 100)
            sig_errs.append(sig / np.sqrt(2 * mask.sum()) * 100)   # err(sigma) = sigma/sqrt(2N)

        centers  = np.array(centers)
        sigmas   = np.array(sigmas)
        sig_errs = np.array(sig_errs)
        means    = np.array(means)

        # left panel resolution (sigma) vs pT
        axes[0].errorbar(centers, sigmas, yerr=sig_errs,
                         fmt=f"{st['marker']}-", color=st["color"],
                         label=st["label"], capsize=4, linewidth=1.5)
        # right panel bias (mean) vs pT
        axes[1].plot(centers, means, f"{st['marker']}-",
                     color=st["color"], label=st["label"], linewidth=1.5)

    for ax, ylabel, title in zip(
        axes,
        [r"$\sigma(\Delta p_T/p_T)$ [%]", r"Mean $\Delta p_T/p_T$ [%]"],
        [r"Muon $p_T$ Resolution", r"$p_T$ Bias"]
    ):
        ax.set_xlabel(r"True $p_T$ [MeV]", fontsize=12)
        ax.set_ylabel(ylabel, fontsize=12)
        ax.set_title(title, fontsize=13)
        ax.legend(fontsize=11)
        ax.grid(alpha=0.3)
        ax.set_xlim(bins[0], bins[-1])

    fig.suptitle("Muon $p_T$ Resolution: BIB Comparison", fontsize=14, fontweight="bold")
    fig.tight_layout()
    _save(fig, cfg["out_dir"], "01_pt_resolution.png", cfg["dpi"])


def plot_efficiency(datasets: dict, bins, cfg):
    
    """plot reconstruction efficiency vs true pT
    efficiency = N(matched reco) / N(truth muons) per pT bin
    error bars use the wilson score interval which is more accurate than
    the naive binomial error, especially near 0% or 100%
    """
    fig, ax = plt.subplots(figsize=(7, 5))

    for tag, arr in datasets.items():
        st = STYLE[tag]
        effs, errs, centers = [], [], []

        for lo, hi in zip(bins[:-1], bins[1:]):
            # use all_true_pt (includes unmatched) for the denominator
            mask  = (arr["all_true_pt"] >= lo) & (arr["all_true_pt"] < hi)
            n_tot = mask.sum()
            if n_tot < cfg["min_events_per_bin"]:
                continue
            n_match = arr["all_matched"][mask].sum()
            eff = n_match / n_tot
            # WHAT IS IT DOING HERE?? WHAT IS A WILSON SCORE?
            # wilson score interval: more reliable than sqrt(p(1-p)/n) near 0 or 1
            z     = 1.96   # 95% confidence level
            denom = 1 + z**2 / n_tot
            p_hat = (eff + z**2 / (2 * n_tot)) / denom
            err   = z * np.sqrt(eff * (1 - eff) / n_tot + z**2 / (4 * n_tot**2)) / denom
            effs.append(p_hat * 100)
            errs.append(err * 100)
            centers.append(0.5 * (lo + hi))

        ax.errorbar(centers, effs, yerr=errs,
                    fmt=f"{st['marker']}-", color=st["color"],
                    label=st["label"], capsize=4, linewidth=1.5)

    ax.set_xlabel(r"True $p_T$ [MeV]", fontsize=12)
    ax.set_ylabel("Reconstruction Efficiency [%]", fontsize=12)
    ax.set_title("Muon Reconstruction Efficiency", fontsize=13)
    ax.set_ylim(0, 105)
    ax.axhline(100, color="gray", linestyle="--", linewidth=0.8)   # ideal 100% line
    ax.legend(fontsize=11)
    ax.grid(alpha=0.3)
    ax.set_xlim(bins[0], bins[-1])
    fig.tight_layout()
    _save(fig, cfg["out_dir"], "02_efficiency.png", cfg["dpi"])


def plot_angular_resolution(datasets: dict, bins, cfg):
    
    """plot angular resolution (sigma of delta_eta and delta_phi) vs true pT
    angular resolution measures how well the direction of the muon is reconstructed,
    independent of the momentum magnitude. for the muon collider with BIB, this is
    expected to be better preserved than pT resolution since BIB adds random hits
    that bias curvature (pT) more than direction
    """
    fig, axes = plt.subplots(1, 2, figsize=(13, 5))

    for tag, arr in datasets.items():
        st    = STYLE[tag]
        d_eta = arr["reco_eta"] - arr["true_eta"]
        d_phi = arr["reco_phi"] - arr["true_phi"]
        # dphi [-pi, pi] to handle boundary crossing
        d_phi = (d_phi + np.pi) % (2 * np.pi) - np.pi

        for ax, residual, ylabel in zip(
            axes,
            [d_eta, d_phi],
            [r"$\sigma(\Delta\eta)$", r"$\sigma(\Delta\phi)$ [rad]"],
        ):
            centers, sigmas, sig_errs = [], [], []
            for lo, hi in zip(bins[:-1], bins[1:]):
                mask = (arr["true_pt"] >= lo) & (arr["true_pt"] < hi)
                if mask.sum() < cfg["min_events_per_bin"]:
                    continue
                _, sig, _ = gauss_fit(residual[mask])
                centers.append(0.5 * (lo + hi))
                sigmas.append(sig)
                sig_errs.append(sig / np.sqrt(2 * mask.sum()))

            ax.errorbar(centers, sigmas, yerr=sig_errs,
                        fmt=f"{st['marker']}-", color=st["color"],
                        label=st["label"], capsize=4, linewidth=1.5)
            ax.set_xlabel(r"True $p_T$ [MeV]", fontsize=12)
            ax.set_ylabel(ylabel, fontsize=12)
            ax.legend(fontsize=11)
            ax.grid(alpha=0.3)
            ax.set_xlim(bins[0], bins[-1])

    axes[0].set_title(r"$\eta$ Resolution", fontsize=13)
    axes[1].set_title(r"$\phi$ Resolution", fontsize=13)
    fig.suptitle("Muon Angular Resolution: BIB Comparison", fontsize=14, fontweight="bold")
    fig.tight_layout()
    _save(fig, cfg["out_dir"], "03_angular_resolution.png", cfg["dpi"])


"""def plot_pulls(datasets: dict, cfg):
    
    ADD TRIP STRING BACK IF UNCOMMENTED plot track parameter pull distributions
    a pull = (measured - truth) / uncertainty. if the track fit is well-calibrated,
    pulls should follow a unit gaussian (mean=0, sigma=1). deviations indicate
    biased measurements or over/underestimated uncertainties
    
    currently these are mostly empty because SiTracksMCTruthLink is not available
    in these files — the pull arrays will be length 0 and nothing is plotted
    the dashed black line shows the ideal unit gaussian for reference
    ADD TRIP STRING BACK IF UNCOMMENTED
    
    param_labels = {
        "pull_d0":     r"$d_0 / \sigma_{d_0}$",
        "pull_z0":     r"$z_0 / \sigma_{z_0}$",
        "pull_phi":    r"$\Delta\phi / \sigma_\phi$",
        "pull_tanlam": r"$\Delta\tan\lambda / \sigma_{\tan\lambda}$",
        "pull_omega":  r"$\omega / \sigma_\omega$",
    }

    fig, axes = plt.subplots(1, len(param_labels), figsize=(18, 4))

    for ax, (key, xlabel) in zip(axes, param_labels.items()):
        x_range = (-5, 5)
        for tag, arr in datasets.items():
            st   = STYLE[tag]
            vals = arr[key]
            if len(vals) == 0:
                continue
            vals = np.clip(vals, *x_range)   # clip outliers for display
            counts, edges = np.histogram(vals, bins=50, range=x_range)
            centers = 0.5 * (edges[:-1] + edges[1:])
            ax.step(centers, counts, color=st["color"], label=st["label"],
                    linewidth=1.5, where="mid")
            _, sig, ok = gauss_fit(vals)
            if ok:
                x_fit = np.linspace(*x_range, 300)
                scale = counts.max()
                # ideal unit gaussian for comparison
                ax.plot(x_fit,
                        scale * np.exp(-0.5 * x_fit**2),
                        "k--", linewidth=1, alpha=0.5,
                        label="Ideal" if tag == list(datasets.keys())[0] else "")
                ax.set_title(f"{xlabel}\n$\\sigma = {sig:.3f}$", fontsize=10)

        ax.set_xlabel(xlabel, fontsize=10)
        ax.set_ylabel("Entries", fontsize=10)
        ax.legend(fontsize=8)
        ax.grid(alpha=0.3)

    fig.suptitle("Track Parameter Pulls: BIB Comparison", fontsize=13, fontweight="bold")
    fig.tight_layout()
    _save(fig, cfg["out_dir"], "04_track_pulls.png", cfg["dpi"])"""


def plot_residual_distributions(datasets: dict, cfg):
    
    """plot pT residual distributions: full range and zoomed core peak
    left panel: full range histogram showing the complete residual distribution
    including BIB failure events. the spike near -100% (now removed by the
    track + PDG filters) would appear here if matching were poor
    
    right panel: zoomed to +-30% with a gaussian fit to the core peak
    the fit captures well-reconstructed muons only. counts.max() is used
    to anchor the gaussian amplitude to the tallest histogram bar
    mu = bias (should be near 0%), sigma = core resolution
    """
    fig, axes = plt.subplots(1, 2, figsize=(12, 5))

    for tag, arr in datasets.items():
        st  = STYLE[tag]
        res = (arr["reco_pt"] - arr["true_pt"]) / arr["true_pt"] * 100

        # left panel full range to show any BIB failure tails
        axes[0].hist(res, bins=100, color=st["color"], alpha=0.7,
                     edgecolor="k", linewidth=0.3)
        axes[0].set_xlabel(r"$(p_T^{\rm reco} - p_T^{\rm true})/p_T^{\rm true}$ [%]", fontsize=11)
        axes[0].set_ylabel("Events", fontsize=11)
        axes[0].set_title("Full Range (BIB failures visible)", fontsize=12)
        axes[0].grid(alpha=0.3)

        # right panel core peak only — excludes large residuals from BIB
        core   = res[(res > -30) & (res < 30)]
        n_bins = 60
        counts, edges, _ = axes[1].hist(core, bins=n_bins, range=(-30, 30),
                                         color=st["color"], alpha=0.7,
                                         edgecolor="k", linewidth=0.3,
                                         label="Core events")
        if len(core) > 10:
            mu, sig, ok = gauss_fit(core)
            if ok:
                x = np.linspace(-30, 30, 300)
                # anchor gaussian peak to the tallest bin in THIS histogram
                axes[1].plot(x, gaussian(x, counts.max(), mu, sig),
                             "k-", linewidth=2,
                             label=rf"$\mu={mu:.2f}\%$, $\sigma={sig:.2f}\%$")
        axes[1].set_xlabel(r"$(p_T^{\rm reco} - p_T^{\rm true})/p_T^{\rm true}$ [%]", fontsize=11)
        axes[1].set_ylabel("Events", fontsize=11)
        axes[1].set_title("Core Peak (well-reconstructed muons)", fontsize=12)
        axes[1].legend(fontsize=10)
        axes[1].grid(alpha=0.3)

    fig.suptitle(f"$p_T$ Residual — {STYLE[list(datasets.keys())[0]]['label']}",
                 fontsize=13, fontweight="bold")
    fig.tight_layout()
    _save(fig, cfg["out_dir"], "00_residual_distributions.png", cfg["dpi"])


def _save(fig, out_dir, fname, dpi):
    """save figure to disk and close it to free memory."""
    os.makedirs(out_dir, exist_ok=True)
    path = os.path.join(out_dir, fname)
    fig.savefig(path, dpi=dpi, bbox_inches="tight")
    print(f"  Saved → {path}")
    plt.close(fig)


# ── main ──────────────────────────────────────────────────────────────────────

def main():
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--filelist", type=str, default=None,
                        help="override filelist path (e.g. xrootd version for batch jobs)")
    args = parser.parse_args()

    cfg = CONFIG

    # allow overriding the filelist from the command line — used by run_analysis.sh
    # when submitting to OSG where filelist_xrootd.txt has xrootd-prefixed paths
    if args.filelist:
        cfg = dict(cfg)
        cfg["filelist"] = args.filelist

    # ── collect files ──────────────────────────────────────────────────────
    no_bib_files = sorted(glob.glob(cfg["no_bib_glob"])) if cfg["no_bib_glob"] else []

    if cfg.get("filelist"):
        with open(cfg["filelist"]) as f:
            bib_files = sorted([l.strip() for l in f if l.strip()])
    elif cfg["bib_glob"]:
        bib_files = sorted(glob.glob(cfg["bib_glob"]))
    else:
        bib_files = []

    if not no_bib_files and not bib_files:
        sys.exit("no files found. check filelist.txt or glob patterns in CONFIG.")

    print(f"No-BIB files : {len(no_bib_files)}")
    print(f"BIB files    : {len(bib_files)}")

    datasets = {}

    if no_bib_files:
        print("\nProcessing no-BIB files …")
        datasets["no_bib"] = process_files(no_bib_files, cfg).arrays()

    if bib_files:
        print("\nProcessing BIB files …")
        datasets["bib"] = process_files(bib_files, cfg).arrays()

    if len(datasets) == 1:
        print("\nSingle-dataset mode — all plots will show one dataset only.")

    # sanity check: print total truth muons, matched count, and overall efficiency
    for tag, arr in datasets.items():
        n  = len(arr["all_true_pt"])
        nm = arr["all_matched"].sum()
        print(f"\n[{STYLE[tag]['label']}]  truth muons: {n}  |  matched: {nm}  |  eff: {nm/n*100:.1f}%")

    # ── generate plots ─────────────────────────────────────────────────────
    bins = cfg["pt_bins"]
    print("\nGenerating plots …")
    plot_residual_distributions(datasets, cfg)
    plot_pt_resolution(datasets, bins, cfg)
    plot_efficiency(datasets, bins, cfg)
    plot_angular_resolution(datasets, bins, cfg)
    #plot_pulls(datasets, cfg) UNCOMMENT IF INCLUDING 

    print(f"\n plots saved to '{cfg['out_dir']}/'")


if __name__ == "__main__":
    main()